### ISSUE TITLE
Add Drush 8 as an option

### ISSUE THREAD

**Issue by jazzdrive3** [Lullabot/trusty32-lamp#18]
Currently, the default drush installed is Drush 6. I think Drush 8 at least needs to be an option, and part of the initial provisioning, even if it has a different alias.

**Comment by jazzdrive3** [comment]
Composer will also be required to get Drush 8 running.

**Comment by m4olivei** [comment]
@jazzdrive3 looks like Drush 8 gets aliases as `drush8` in the vagrant box.  How do you tell your local drush to use that alias with remote commands to the vagrant box?

**Comment by deviantintegral** [comment]
This is what I have @m4olivei . Does this make more sense as something to modify locally as-is today, or offer as a separate alias for drush 8?

I guess Drush 8 is now stable, so we could just move to that directly?

```diff
diff --git a/site-aliases/aliases.drushrc.php b/site-aliases/aliases.drushrc.php
index 4a0f3ea..87a3eb8 100644
--- a/site-aliases/aliases.drushrc.php
+++ b/site-aliases/aliases.drushrc.php
@@ -43,5 +43,8 @@ if (isset($matches[1])) {
     'remote-user' => 'vagrant',
     'ssh-options' => "-i " . $private_key,
     'root' => '/var/www/docroot',
+    'path-aliases' => array(
+      '%drush-script' => '/usr/local/bin/drush8',
+    ),
   );
 }
```

**Comment by m4olivei** [comment]
@deviantintegral thanks that works, wasn't aware of that Drush alias option.  I think it makes sense as-is.  Adding another alias seems repetitive, you'd likely only use one or the other according to the version of Drupal in the box.  

As for moving to Drush 8 as the default (is that what your asking?), you still need to use Drush 8 for D8 and Drush 7 for D7 right?  Unless that's changed, I think it's OK to default the `drush` alias in the box to Drush 7.

Anyways, thanks for the tip Andrew!

**Comment by deviantintegral** [comment]
Drush 8 is supposed to work with Drupal 6 and 7. However, I haven't actually used it on D7 so I don't know if there's any compatibility breaks to be aware of.

**Comment by m4olivei** [comment]
Orly??  I've been assuming Drush 7 for D7 and Drush 8 for D8 from Karens article.  Maybe I should try just using Drush 8 for all the things and see how it goes.
