### ISSUE TITLE
Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by jazzdrive3** [Lullabot/trusty32-lamp#21]
Setting up a 64bit box for the first time, so it needs to download the box. Get this error:
```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
```
Failed on this command:
```Downloading: https://cdn.rawgit.com/Lullabot/trusty32-lamp/master/trusty64-lamp.json```

**Comment by deviantintegral** [comment]
Can you double check you're on the latest release? I just removed the 64-bit box and am downloading it now.

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'trusty64-lamp' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'https://cdn.rawgit.com/Lullabot/trusty32-lamp/master/trusty64-lamp.json'
    default: URL: https://cdn.rawgit.com/Lullabot/trusty32-lamp/master/trusty64-lamp.json
==> default: Adding box 'trusty64-lamp' (v0.1.0) for provider: virtualbox
    default: Downloading: https://www.dropbox.com/s/vu0lz1kl0kafx8u/trusty64-lamp.box?dl=1
```

**Comment by jazzdrive3** [comment]
Strange. Mine isn't loading the metadata or setting the URL before adding the box and downloading. I do have the latest. Triple checked that just now.

I manually downloaded the box and added it, and its working fine, so there was nothing wrong with the URL.

**Comment by deviantintegral** [comment]
Latest vagrant too?

**Comment by jazzdrive3** [comment]
Oh. No :). I should remember to always try that first. Updated and it looks like its downloading fine.

I'll just be standing over here in the corner.
