### ISSUE TITLE
Upgrade PHP to 5.6

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/trusty32-lamp#29]
The base box comes with PHP 5.5.  Many client environments are at or will be moving soon to PHP 5.6.  Would be good to have an option to update to PHP 5.6.  Admittedly, I know little about the best way to update the Vagrant box to PHP 5.6.  Just documenting here, and will help where I can.  

As a largely uninformed first step, I went ahead and tried the update on a fresh box following this article: https://www.dev-metal.com/install-setup-php-5-6-ubuntu-14-04-lts/, which uses this PPA for PHP-5.6: https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6.  Seemed to work rather smoothly, however I lost xhprof support in the process.

Just wanted to get this rolling.  I'll try and spend some time on it when I have some time to play around with this, as I'm a total n00b when it comes to this stuff.

**Comment by deviantintegral** [comment]
xhprof has been forked into uprofiler, which is what I see in the 5.6 repository. Or did that break? We'd need to rename the ini file I think.

https://github.com/FriendsOfPHP/uprofiler

(though it's concerning that project hasn't seen activity in a year)

**Comment by deviantintegral** [comment]
I just pushed updates to the virtualbox boxes bundling PHP 5.5, 5.6, and 7.0. See the [release notes for 1.2](https://github.com/Lullabot/trusty32-lamp/releases/tag/1.2) for details.
