### ISSUE TITLE
Trying to update base box errors out

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/trusty32-lamp#30]
Looks like maybe the links to the base box are out of date? Here is the output I get following the instructions to update the base box:

```
$ vagrant box update
==> default: Checking for updates to 'deviantintegral/trusty32-lamp'
    default: Latest installed version: 1.1.3
    default: Version constraints:
    default: Provider: virtualbox
There was an error while downloading the metadata for this box.
The error message is shown below:



```

I found what appear to be links to the base box in `trusty32-lamp.json` and `trusty64-lamp.json`:

* https://www.dropbox.com/sh/oy1av6uhod3yeto/AADzTDkFKJ2qXflAvJh57FKla/trusty32-lamp.box?dl=1
* https://www.dropbox.com/s/vu0lz1kl0kafx8u/trusty64-lamp.box?dl=1
* https://www.dropbox.com/s/jqz8tstjh739wra/trusty64-lamp-vmware.box?dl=1

These all 404 ATM.

**Comment by deviantintegral** [comment]
I know we got you up and running, but before that, did you git pull on the repository? That should have updated everything to point to Atlas instead of Dropbox.

**Comment by m4olivei** [comment]
Yeah I was on the latest. My problem was the same as those in this thread: 

https://github.com/mitchellh/vagrant/issues/5016#issuecomment-260065012

In the end, I believe all is well here and we can close this out.
