### ISSUE TITLE
VirtualBox version

### ISSUE THREAD

**Issue by mtift** [Lullabot/trusty32-lamp#41]
It looks like this does not support VirtualBox 5.2 (the latest version: https://www.virtualbox.org). When I tried to install it would not let me and listed 5.1 and a few earlier versions of VirtualBox.When I switched to VirtualBox 5.1 it worked.

So maybe the README should say VirtualBox 5.1 or earlier?

**Comment by deviantintegral** [comment]
Is this fixed for you now that you've upgraded Vagrant?

**Comment by mtift** [comment]
Yes! I was using the [version of vagrant in Debian stable](https://packages.debian.org/stable/admin/vagrant) (1.9.1), so I updated vagrant to the latest version (2.0.2). After doing that I installed VitualBox 5.2.6 and it all works. Thanks!
