### ISSUE TITLE
install to www/docroot

### ISSUE THREAD

**Issue by mtift** [Lullabot/trusty32-lamp#43]
This in the README:

```
    $ cd www
    $ rm -rfv docroot
    $ cd ..
```

Is followed by:

> Go to drupal.org to clone Drupal 8 to get directions to checkout Drupal. It needs to be cloned into the `www/docroot` directory within your project directory.

So it seems like given the `git clone` example that `cd ..` should be removed?

**Comment by deviantintegral** [comment]
Yep. Totally.
