### ISSUE TITLE
Git branch

### ISSUE THREAD

**Issue by mtift** [Lullabot/trusty32-lamp#47]
When I `vagrant ssh` into my machine that uses the supplied oh-my-xsh   theme (`ZSH_THEME="superjarin"`, or any other theme for that matter) I don't see a git branch on the prompt. For example, I just see this:

```
[] /vagrant/www/docroot 
```

If I add something like this to my ~/.zshrc:

```
autoload -Uz vcs_info
precmd () { vcs_info }
setopt prompt_subst
PS1="\$vcs_info_msg_0_$PS1"
```

Then I see this in my prompt:

```
 (git)-[master]-[] /vagrant/www/docroot
```

Should I see git branches using the project with the default setup?

**Comment by deviantintegral** [comment]
Interesting. I wonder if it's a bug because dirty file tracking is disabled. Also, the theme should be the default of `robbyrussell`. I wonder how yours got there?

**Comment by deviantintegral** [comment]
So you have to add the `git-prompt` plugin to get it to be added by default. However, that slows down any prompt displays for a mounted `/var/www/docroot` pretty significantly, so I removed it (a long) time ago. Do you think displaying the branch by itself is worth it? For me, I'm almost always working from outside the VM for git operations.

**Comment by q0rban** [comment]
> For me, I'm almost always working from outside the VM for git operations.

/me too.

**Comment by mtift** [comment]
Thanks for the feedback. It sounds like the answer to my question is "no."

I haven't done any git operations in the VM, either. I have just noticed that I've been typing `git branch` when I'm in the VM, troubleshooting problems, including making sure I'm on the right branch.

**Comment by mtift** [comment]
Oh, and yes, I meant "robbyrussell."
