### ISSUE TITLE
Ancient PHP version

### ISSUE THREAD

**Issue by mtift** [Lullabot/trusty32-lamp#48]
Is there any chance that this could support PHP 5.3.3? I'm working with a client that uses PHP 5.3.3 version in production (which. incidentally, is the lowest version of PHP that [Behat supports](http://docs.behat.org/en/latest/quick_start.html)).

**Comment by deviantintegral** [comment]
Oh dear, 5.3 was EOL'ed in 2014! I'm not too keen on including it in the default image unless someone has built packages that follow the same parallel / config layout as the existing packages. Otherwise, I think it would have to be built from source.
