### ISSUE TITLE
Xdebug config

### ISSUE THREAD

**Issue by mtift** [Lullabot/trusty32-lamp#49]
I've been trying to get Xdebug working (with [vdebug](https://github.com/joonty/vdebug) in vim). This setup has been working great for me (for many years) on local sites when I add this to etc/php/7.0/apache2/php.ini:

```
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.idekey=''
xdebug.max_nesting_level=256
```

I've been playing around with various hosts (e.g. 127.0.0.1), ports, and other configuration, but I can't seem to get xdebug to work with this LAMP setup. Any suggestions for me?

**Comment by deviantintegral** [comment]
`localhost` means local within the VM, so if you're running vim outside you'll need to change the hostname or IP address. Otherwise, you could follow what the VM does by default and use remote_connect_back plus a browser bookmarklet / extension to set the xdebug cookies.
